CourseworkApp/Controllers/ConferenceCallsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseworkApp.Models;

namespace CourseworkApp.Controllers
{
    public class ConferenceCallsController : Controller
    {
        private AppDB db = new AppDB();

        // GET: ConferenceCalls
        public ActionResult Index()
        {
            return View(db.ConferenceCalls.ToList());
        }

        // GET: ConferenceCalls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConferenceCall conferenceCall = db.ConferenceCalls.Find(id);
            if (conferenceCall == null)
            {
                return HttpNotFound();
            }
            return View(conferenceCall);
        }

        // GET: ConferenceCalls/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ConferenceCalls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ConferenceCallID,ConferenceCallTitle,ConferenceCallDate,ConferenceCallTranscript")] ConferenceCall conferenceCall)
        {
            if (ModelState.IsValid)
            {
                db.ConferenceCalls.Add(conferenceCall);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(conferenceCall);
        }

        // GET: ConferenceCalls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConferenceCall conferenceCall = db.ConferenceCalls.Find(id);
            if (conferenceCall == null)
            {
                return HttpNotFound();
            }
            return View(conferenceCall);
        }

        // POST: ConferenceCalls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ConferenceCallID,ConferenceCallTitle,ConferenceCallDate,ConferenceCallTranscript")] ConferenceCall conferenceCall)
        {
            if (ModelState.IsValid)
            {
                db.Entry(conferenceCall).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(conferenceCall);
        }

        // GET: ConferenceCalls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConferenceCall conferenceCall = db.ConferenceCalls.Find(id);
            if (conferenceCall == null)
            {
                return HttpNotFound();
            }
            return View(conferenceCall);
        }

        // POST: ConferenceCalls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ConferenceCall conferenceCall = db.ConferenceCalls.Find(id);
            db.ConferenceCalls.Remove(conferenceCall);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseworkApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css") 
    @Scripts.Render("~/bundles/modernizr")
 

</head>
<style>
    .jumbotron {
        background-image: url("https://www.planwallpaper.com/static/images/9Zk2kcY.jpg");
    }

    .head {
        font-size: 42px;
        color: white;
        text-shadow: 1px 1px black;
    }

    .lead {
        padding-left: 5%;
        color: white;
        text-shadow: 1px 1px black;
    }
   .boxArea {
        background-color: #f7f7f9;
        border: 1px solid lightgrey;
        border-radius: 5px;
        margin-top: 5%;
        text-align: center;
    }
  
</style>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Research 'R' Us", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Events", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Admin Panel", "AdminPanel", "Home")</li>
                    }
                    <li>@Html.ActionLink("Reports", "Reports", "Home")</li>
                    <li>@Html.ActionLink("Publications", "Publications", "Home")</li>
                    <li>@Html.ActionLink("Conference Calls", "ConferenceCalls", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="jumbotron">
        <p class="head">Research 'R' Us</p>
        <p class="lead">We do stuff. </p>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dominic Brett</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>